# Generated by Django 3.2.9 on 2021-11-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20211118_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sugar',
        ),
    ]
