# Generated by Django 3.2.9 on 2021-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_remove_cartitem_sugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sugar',
            field=models.TextField(blank=True),
        ),
    ]
