# Generated by Django 3.2.9 on 2021-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_cartitem_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sugar',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
